### ISSUE TITLE
Error when running baseline BiMPM

### ISSUE THREAD

**Issue by Owenchan2001** [declare-lab/SANCL#4]
十分感谢开源代码！但是当运行baseline bimpm时，会产生如下报错：
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    run(args.config, args.stage, args.ckpt)
  File "G:\RHP\SANCL\matchzoo\utils\modeling.py", line 40, in run
    model = build(configs, stage, ckpt, rank=rank)
  File "G:\RHP\SANCL\matchzoo\utils\modeling.py", line 18, in build
    return modeling(configs, stage, ckpt, *args, **kwargs)
  File "G:\RHP\SANCL\matchzoo\engine\base_modeling.py", line 42, in __init__
    self.modeling()
  File "G:\RHP\SANCL\matchzoo\engine\base_modeling.py", line 54, in modeling
    self.build_dataloader_callback()
  File "G:\RHP\SANCL\matchzoo\modeling\rhp_modeling.py", line 186, in build_dataloader_callback
    self.preprocessor.prd_text_field.vocab.pad_index,
AttributeError: 'NoneType' object has no attribute 'pad_index'
请问是否可以看看问题是什么导致的呢555

**Comment by Clement25** [comment]
你可以尝试下给pad_index赋值

**Comment by Owenchan2001** [comment]
谢谢，我去尝试一下
